### ISSUE TITLE
App Structure

### ISSUE THREAD

**Issue by oneEyedSunday** [oneEyedSunday/workflow#11]
Structure the frontend.
Pages
* [x] Auth
* [x] Projects
* [x] Forms
* [x] Documents (_optional_) 
* [x] Dashboard will have a calendar

**Comment by oneEyedSunday** [comment]
@ogbanugot can you remind me what we decided about `Documents`?

**Comment by ogbanugot** [comment]
> @ogbanugot can you remind me what we decided about `Documents`?

Its just a simple document upload but we are thinking maybe we should add it to the task part. What i mean is as you add a task, it can either be a form task (which the user has already created) or a document task which the user will now upload there at once. Maybe the upload will be a modal that will just allow the user upload the document or something like that.

**Comment by oneEyedSunday** [comment]
Ok, I think we'd add a `➕New Document` & `➕ New Form` to the task creation.
That way you can just create the form or doc from there.
It may be tricky opening the form creation template in a modal because of `accessibility` and the user mistakenly closing the modal while still typing. 
These can be remedied, but I don't think we can invest that time atm.
