### ISSUE TITLE
Set up hosting for the API

### ISSUE THREAD

**Issue by oneEyedSunday** [oneEyedSunday/workflow#6]
Set up hosting so the API is live.
It'd be nice to have some sort of API documentation e.g. `POSTMAN` or `Swagger docs` to reduce reliance on direct communication with whoever implemented endpoint(s).

For the backend, the repo should be separate. Add a link to the repo to the [docs](https://github.com/oneEyedSunday/workflow/tree/master/docs)

**Comment by ogbanugot** [comment]
API is live;
Swagger docs added

**Comment by oneEyedSunday** [comment]
API Docs [here](https://workflow801.herokuapp.com/schema/)
API home [url](https://workflow801.herokuapp.com/account/login/)

**Comment by ogbanugot** [comment]
> API Docs [here](https://workflow801.herokuapp.com/schema/)
> API home [url](https://workflow801.herokuapp.com/account/login/)

Nice, thanks.
